//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrat_ecole
    {
        public int idcontrat_ecole { get; set; }
        public byte[] fichier_contrat { get; set; }
        public Nullable<int> ecole_id { get; set; }
        public Nullable<int> artiste_id { get; set; }
    }
}
