//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_artiste
    {
        public long id_document_artiste { get; set; }
        public long id_artiste { get; set; }
        public string type_dossier { get; set; }
        public byte[] pdf { get; set; }
    }
}
