//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_entreprise
    {
        public int iddocument_entreprise { get; set; }
        public int id_entreprise { get; set; }
        public byte[] Attestation_assurance { get; set; }
        public byte[] Kbis { get; set; }
        public byte[] RIB { get; set; }
        public byte[] Dernier_statut { get; set; }
    }
}
