//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecole()
        {
            this.artistes = new HashSet<artiste>();
            this.formation_ecole = new HashSet<formation_ecole>();
        }
    
        public long idecole { get; set; }
        public string nom { get; set; }
        public string SIRET { get; set; }
        public string categorie { get; set; }
        public string nom_du_responsable { get; set; }
        public string prenom_du_responsable { get; set; }
        public string adresse { get; set; }
        public string code_postale { get; set; }
        public string ville { get; set; }
        public string pays { get; set; }
        public string numero { get; set; }
        public string adresse_mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artiste> artistes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formation_ecole> formation_ecole { get; set; }
    }
}
