//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formation_ecole
    {
        public long idformation_ecole { get; set; }
        public long formation_id { get; set; }
        public long ecole_id { get; set; }
        public Nullable<int> cout_de_formation { get; set; }
    
        public virtual ecole ecole { get; set; }
        public virtual fomation fomation { get; set; }
    }
}
