//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class art_fundingEntities2 : DbContext
    {
        public art_fundingEntities2()
            : base("name=art_fundingEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artiste> artistes { get; set; }
        public virtual DbSet<categorie> categories { get; set; }
        public virtual DbSet<contrat_abonnement> contrat_abonnement { get; set; }
        public virtual DbSet<contrat_ecole> contrat_ecole { get; set; }
        public virtual DbSet<contrat_entreprise> contrat_entreprise { get; set; }
        public virtual DbSet<document_artiste> document_artiste { get; set; }
        public virtual DbSet<document_entreprise> document_entreprise { get; set; }
        public virtual DbSet<ecole> ecoles { get; set; }
        public virtual DbSet<entreprise> entreprises { get; set; }
        public virtual DbSet<fomation> fomations { get; set; }
        public virtual DbSet<formation_ecole> formation_ecole { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<utilisateurartiste> utilisateurartistes { get; set; }
        public virtual DbSet<utilisateurentreprise> utilisateurentreprises { get; set; }
    }
}
