//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        public int idprojet { get; set; }
        public byte[] un_photo { get; set; }
        public byte[] deux_photo { get; set; }
        public byte[] trois_photo { get; set; }
        public byte[] quatre_photo { get; set; }
        public byte[] cinq_photo { get; set; }
        public byte[] six_photo { get; set; }
        public byte[] sept_photo { get; set; }
        public byte[] huit_photo { get; set; }
        public byte[] neuf_photo { get; set; }
        public byte[] dix_photo { get; set; }
        public byte[] onze_photo { get; set; }
        public byte[] douze_photo { get; set; }
        public byte[] treize_photo { get; set; }
        public byte[] quatorze_photo { get; set; }
        public byte[] quinze_photo { get; set; }
    }
}
