//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateurartiste
    {
        public int idUtilisateurArtiste { get; set; }
        public string mailUA { get; set; }
        public string mot_de_passe { get; set; }
        public Nullable<int> idartiste { get; set; }
    
        public virtual artiste artiste { get; set; }
    }
}
