//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_fundingV0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class utilisateurartiste
    {
        public int idUtilisateurArtiste { get; set; }
        [Display(Name = "Adresse email")]
        public string mailUA { get; set; }
        [Display(Name = "Mot de passe")]
        public string mot_de_passe { get; set; }
        public Nullable<int> idartiste { get; set; }
        public string role { get; set; }
    
        public virtual artiste artiste { get; set; }
    }
}
